allowBuilds:
  '@reown/appkit': true
  bufferutil: set this to true or false
  esbuild: true
  keccak: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  utf-8-validate: set this to true or false
minimumReleaseAgeExclude:
  - openai@6.46.0
