allowBuilds:
  '@reown/appkit': true
  esbuild: true
  bufferutil: true
  keccak: true
  sharp: true
  utf-8-validate: true
  msw: false

minimumReleaseAgeExclude:
  - openai@6.46.0

overrides:
  hono: 4.12.25

onlyBuiltDependencies:
  - bufferutil
  - keccak
  - sharp
  - utf-8-validate
